[package]
name = "shared_document"
version = "0.1.0"
edition = "2021"

[dependencies]
autosurgeon = { workspace = true }
automerge = { workspace = true }
automerge_repo = { workspace = true }
futures = { workspace = true }
