[package]
name = "prompts"
version = "0.1.0"
edition = "2021"

[dependencies]
shared_document = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
mockall = "0.12"
